# Declare the build locale
language: android
# Configuration information
android:
  components:
    - build-tools-28.0.3
    - android-28
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
script:
  - ./gradlew assembleRelease

deploy:
  provider: releases
  # Github oauth token
  api_key: "$GIT_TOKEN"
  # Deployment file path; for Android, deploy the generated apk file
  file:
    - app/build/outputs/apk/release/app-release.apk
  # Avoid Travis CI emptying generated APK files before deployment
  skip_cleanup: true
  # Deploy time
  on:
    # tags set to true means only deployed if there are tags
    tags: false
    branch: master